name: Binary Test

on: [ push, pull_request ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check repos
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Binary Test Calculator
        run: |
          python -m compileall ./tests/calculator.py