name: Docker auto test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v4

      - name: Login and Password to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.USERNAME_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}

      - name: Build and push Docker
        run: |
          docker build -t ${{ secrets.USERNAME_DOCKER }}/devops:ver-${{ github.event.number }} .
          docker push ${{ secrets.USERNAME_DOCKER }}/devops:ver-${{ github.event.number }}